### PR TITLE
Merge utils tests

### PR DESCRIPTION
**Pull request by anosach-luxoft**
PR provides following changes:
- Enable utils tests build
- Correct utils tests according to code changes and make utils tests buildable
- Disable failed tests until they will be fixed in appropriate task

@OHerasym, @dev-gh, @VVeremjova, @AByzhynar, @Kozoriz please review.
This PR contains changes and review notes fixes from [previous PR](https://github.com/anosach-luxoft/sdl_core/pull/17).

### CODE REVIEW

**Comment by VVeremjova** [comment]
@anosach-luxoft Reviewed

**Comment by dev-gh** [comment]
Reviewed

**Comment by OHerasym** [comment]
Reviewed

**Comment by AByzhynar** [comment]
Reviewed

**Pull request merged**
